# name: Build and Deploy to Cloud Run

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Google Cloud auth
#         uses: google-github-actions/auth@v0.4.0
#         with:
#           credentials_json: ${{ secrets.GCP_SA_KEY }}

#       - name: Configure Docker for Google Artifact Registry
#         run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

#       - name: Build the Docker image
#         run: |
#           docker build --no-cache -t asia-northeast1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/remix-rss-reader/app:latest .

#       - name: Push the Docker image
#         run: |
#           docker push asia-northeast1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/remix-rss-reader/app:latest

#       - name: Deploy to Cloud Run
#         run: |
#           gcloud run deploy app \
#             --image asia-northeast1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT }}/remix-rss-reader/app:latest \
#             --platform managed \
#             --region asia-northeast1 \
#             --allow-unauthenticated
